[package]
name = "wit-host"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = { version = "18.0.1", features = ["component-model"] }
wasmtime-wasi = { version = "18.0.2", features = ["tokio"] }